[package]
name="recursive"
type="bin"
authors = ["saleel"]
compiler_version = ">=1.0.0"

[dependencies]
bb_proof_verification = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v3.0.0-nightly.20260102", directory = "barretenberg/noir/bb_proof_verification" }
