c = [
    15,
    219,
    68,
    218,
    28,
    252,
    201,
    77,
    203,
    150,
    78,
    187,
    245,
    18,
    121,
    51,
    66,
    103,
    161,
    194,
    43,
    22,
    179,
    104,
    83,
    124,
    125,
    61,
    12,
    88,
    28,
    78,
]
claimer_priv = "0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc"
eligible_index = 0
eligible_path = [
    "0x000000000000000000000000eb0d0ead45629342654544a478864784784c4853",
    "0x1990ad8cac28f1b5beacc91a2d4374d111232c9b0c671decc0a300a6eefa36a1",
    "0x281b492506eabb5a69bf34cee1820715e2b3538c83f3165026d097b4b63ed81e",
    "0x1bfbf3cd56da0213d75193e53f556e116905d7d2f8b9dfb5b50064c800614d28",
    "0x24df294d3fb172cbad0ef0ad326e0f4d98e46686174d3e4091d9e438f3583114",
    "0x0b9c21b5b7367a8f3e97b6a1f6217dce910331bdc56529a8c0b4338aa640ac5b",
    "0x163801b3a47c9d2dad2c3e7d5511e9bd20e784a4b54791855003306fb158f0b3",
    "0x09b8e64e7144b6fb8c9e98ee26ac2a400b5c244675ec68457ff91ee14a75712f",
    "0x0c334769f943969c5a745776ecbc50e20b7690f65ee7b9cfef98a50375c7aa99",
    "0x2ff43f3c8c57955bfaa7a10c66a33cc0745a8a6eb1d9b2fcc38f3ab86ed4fbd0",
    "0x13b8954fb10179b8c0e96d0d7233542718329c0aa1f6c71d0cc94d28c1d2d8a8",
    "0x1073c2699370674a06680b5de05fb92fc199e8e1c7cd7c960ebeacd1dcb97e05",
]

eligible_root = "0x3061ef7f2408523e3e4653423a49e8f04ac144b13322874ebb03e9138e9830b7"
message = [115, 105, 103, 110, 84, 104, 105, 115]
nullifier_x = [
    222,
    92,
    166,
    18,
    18,
    240,
    217,
    163,
    104,
    159,
    169,
    91,
    44,
    209,
    61,
    150,
    197,
    159,
    50,
    72,
    105,
    72,
    185,
    151,
    35,
    142,
    71,
    21,
    16,
    63,
    194,
    22,
]
nullifier_y = [
    157,
    214,
    151,
    110,
    12,
    59,
    213,
    99,
    230,
    67,
    247,
    172,
    110,
    54,
    68,
    51,
    246,
    55,
    250,
    103,
    29,
    159,
    161,
    225,
    94,
    53,
    76,
    190,
    185,
    97,
    200,
    99,
]
pub_key_x = [
    131,
    24,
    83,
    91,
    84,
    16,
    93,
    74,
    122,
    174,
    96,
    192,
    143,
    196,
    95,
    150,
    135,
    24,
    27,
    79,
    223,
    198,
    37,
    189,
    26,
    117,
    63,
    167,
    57,
    127,
    237,
    117,
]
pub_key_y = [
    53,
    71,
    241,
    28,
    168,
    105,
    102,
    70,
    242,
    243,
    172,
    176,
    142,
    49,
    1,
    106,
    250,
    194,
    62,
    99,
    12,
    93,
    17,
    245,
    159,
    97,
    254,
    245,
    123,
    13,
    42,
    165,
]
s = [
    111,
    133,
    62,
    231,
    89,
    135,
    220,
    230,
    128,
    107,
    89,
    122,
    193,
    212,
    238,
    188,
    167,
    24,
    252,
    24,
    147,
    30,
    237,
    158,
    221,
    242,
    159,
    64,
    209,
    44,
    117,
    108,
]
